apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: mywebapp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec: # Pod spec
      containers:
        - name: mycontainer
          image: phidinh/simple-app
          ports:
            - containerPort: 5000
